- Create Table
CREATE TABLE countries (
video_id PRIMARY KEY,
Canada TEXT,
trend_date_CA TEXT,
title_CA TEXT,
channel_title_CA TEXT,
category_id_CA INT,
views_CA INT,
likes_CA INT,
dislikes_CA INT,
discriptions_CA TEXT,
Great Britain TEXT,
trend_date_GB TEXT,
title_GB TEXT,
channel_title_GB TEXT,
category_id_GB INT,
views_GB INT,
likes_GB INT,
dislikes_GB INT,
discriptions_GB TEXT,
United States TEXT,
tend_date_US TEXT,
title_US TEXT,
channel_title_US TEXT,
category_id_US INT,
views_US INT,
likes_US INT,
dislikes_US INT,
description_US
);